# [START app_yaml]
runtime: nodejs
service: socket-service
env: flex
manual_scaling:
  instances: 1
network:
  session_affinity: true
env_variables:
  BACKEND_URL: "https://test-deploy-382019.uw.r.appspot.com/"
  FRONTEND_URL: "https://rattlechat.netlify.app"
# [END app_yaml]